AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Payment Service for Storage Facilities

Resources:
  PaymentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-Payments
      AttributeDefinitions:
        - AttributeName: payment_id
          AttributeType: S
        - AttributeName: facility_id
          AttributeType: S
      KeySchema:
        - AttributeName: payment_id
          KeyType: HASH
        - AttributeName: facility_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  PaymentsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'OPTIONS,GET,POST,DELETE'"
        AllowOrigin: "'*'"
        AllowCredentials: false

  ProcessPaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: payments_handler.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          PAYMENTS_TABLE: !Ref PaymentsTable
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:Scan
              Resource: !GetAtt PaymentsTable.Arn
      Events:
        CreatePayment:
          Type: Api
          Properties:
            RestApiId: !Ref PaymentsApi
            Path: /payments
            Method: POST
        GetPayments:
          Type: Api
          Properties:
            RestApiId: !Ref PaymentsApi
            Path: /payments
            Method: GET
        CancelPayment:
          Type: Api
          Properties:
            RestApiId: !Ref PaymentsApi
            Path: /payments/{payment_id}
            Method: DELETE

Outputs:
  PaymentsTableName:
    Value: !Ref PaymentsTable
    Description: Name of the DynamoDB table for payments.
  PaymentsApiUrl:
    Value: !Sub "https://${PaymentsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/payments"
    Description: URL for the Payment API
