AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Storage Facilities

Globals:
  Function:
    Runtime: python3.9
    MemorySize: 128
    Timeout: 100
    Tracing: Active

Resources:
  StorageFacilitiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-Facilities
      AttributeDefinitions:
        - AttributeName: facility_id
          AttributeType: S
      KeySchema:
        - AttributeName: facility_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  StorageFacilitiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: storage_facilities.lambda_handler
      Environment:
        Variables:
          FACILITIES_TABLE: !Ref StorageFacilitiesTable
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
              Resource: !GetAtt StorageFacilitiesTable.Arn
      Events:
        GetFacilities:
          Type: Api
          Properties:
            RestApiId: !Ref FacilitiesApi
            Path: /facilities
            Method: GET
        SearchFacilities:
          Type: Api
          Properties:
            RestApiId: !Ref FacilitiesApi
            Path: /facilities/search
            Method: GET

  FacilitiesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${FacilitiesApi}.execute-api.${AWS::Region}.amazonaws.com/${FacilitiesApi.Stage}'

  getFacilitiesApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${FacilitiesApi}.execute-api.${AWS::Region}.amazonaws.com/${FacilitiesApi.Stage}/facilities'

  StorageFacilitiesTable:
    Description: DynamoDB Storage Facilities Table
    Value: !Ref StorageFacilitiesTable

  StorageFacilitiesFunction:
    Description: Lambda Function for Storage Facilities
    Value: !Ref StorageFacilitiesFunction
